[package]
name = "crappy_trading_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#binance = "0.17"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
glob = "0.3"
ron = "0.7.0"

